Unknown proc 'Empty'
Error: (Game.sc) Unknown procedure 'Empty' .  Line: 339, col: 8

Changing to EmptyList doesn't work. Not sure if removing it is ok either.